### ISSUE TITLE
Spotify account without Facebook will say null in the header

### ISSUE THREAD

**Issue by Rouzax** [sandrokl/PlaylistMerger#1]
As described in the Google Play store
![image](https://user-images.githubusercontent.com/4103090/37676373-0d54025e-2c78-11e8-98ab-bd38922f1a50.png)

**Comment by sandrokl** [comment]
Hello @Rouzax . 
Can you please try again with the newest version?
Thanks.

**Comment by Rouzax** [comment]
I have version 1.3.180321.1 currently and the phone does not say there is an update but it still shows `null`

**Comment by Rouzax** [comment]
After an update it now says `Your merged playlists:`

**Comment by sandrokl** [comment]
Great. Thanks for the feedback.
